Project : Bare Metal Forms and Helpers
ozovalihasan/forms-helpers pull request #2
Opened 2020-07-06 09:21 UTC by ozovalihasan

Please review this code for Bare Metal Forms and Helpers, which is a Ruby on Rails project. We;

- Created and migrated a User model with :username, :email and :password
- Built HTML form to add a new user or to edit any user
- Refactor form by using form_tag and form_for helpers

2020-07-06 14:05 UTC, majovanilla requested changes
Hey team, 👋

## You did a *great* job on this project! 💜 

- Good Readme file
- Good Pull Request Message

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Please check the comments I left on your code and make the necessary changes.
- If you are not using a home page, then I suggest you redirect the user to the form immediately, to keep your page user friendly.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  These are completely [Optional] :hedgehog: 

- Improve your form design. You didn't include any CSS styling and the form would look a lot better if you did.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-07-06 14:05 UTC, majovanilla commented on app/controllers/users_controller.rb
> +    redirect_to new_user_path
You should redirect only if the user has been saved.
If the user wasn't saved, you should render again.
See [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_create.png).

2020-07-06 14:05 UTC, majovanilla commented on app/controllers/users_controller.rb
> +  end
You should redirect **only** if the user was updated correctly.
If the user wasn't saved, you should render again.
See [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_update.png).

2020-07-06 14:05 UTC, majovanilla commented on app/views/users/_form.html.erb
> +	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>
Instead of using the hardcoded, you should use `action = users_path`

2020-07-06 14:05 UTC, majovanilla commented on app/views/users/_form.html.erb
> +	<%#= label_tag(:username, "Username:") %>
Instead of using the hardcoded route, you should use `form_tag =(users_path, ...)`
There is no need to include the method here since it's already the default.

2020-07-07 09:12 UTC, ozovalihasan commented
Thanks you @majovanilla for your feedback. It is very clear and helpful. We did followings;

- Used render instead of redirect_to if necessary
- Changed paths formed by hardcoding with paths formed by using _path helper

Unfortunately, we couldn't style it, but we are planning to add some style.

2020-07-07 16:58 UTC, maelfosso approved these changes
# Congratulations :clap: 

Thank you for applying the suggested changes :+1: 
You can merge it now
Good continuation :handshake: 

Mael FOSSO

2020-07-08 07:59 UTC, ozovalihasan commented
Thank you @maelfosso for your feedback.

2020-07-08 08:01 UTC, merged